#
pod 'Masonry'

#
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'AFNetworking', '~> 3.0'

#
pod 'MBProgressHUD'

#
platform :ios, '8.0'
pod 'SDWebImage', '~>3.7'

#
pod 'MJRefresh'